### ISSUE TITLE
'MicroMaestro’ does not name a type

### ISSUE THREAD

**Issue by DaveCalaway** [pololu/maestro-arduino#1]
I have this Issue, on arduino IDE:

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
Arduino: 1.0.6 (Linux), Board: "Arduino Uno"
Basic:40: error: ‘MicroMaestro’ does not name a type
Basic.ino: In function ‘void loop()’:
Basic:57: error: ‘maestro’ was not declared in this scope

**Comment by ryantm** [comment]
Hello, Dave.

Can you simplify your Basic.ino code to the simplest code that generates this error and post it here? Also, if you post the version of your Arduino IDE and what OS you are running it might help in reproducing it.

Ryan

**Comment by DaveCalaway** [comment]
I loaded the sample code " base.ino " that I found on this page.

**Comment by ryantm** [comment]
It sounds like you didn't load the Basic.ino example from the examples menu. Can you install the library according to the instructions in the [readme file](https://github.com/pololu/maestro-arduino#software)? Then, you should be able to load the Basic example sketch from Arduino IDE's File->Examples menu.

Ryan

**Comment by DaveCalaway** [comment]
I'm sorry, the problem was in the arduino IDE for ubuntu. I solved.
Thank you very much.
