### ISSUE TITLE
Change baud rate?

### ISSUE THREAD

**Issue by olavkvern** [pololu/maestro-arduino#2]
Is there a way to change the baud rate from 9600?

Thanks,

Ole

**Comment by ryantm** [comment]
Hi, Ole.

Sure, but you have to change it in two places. You need to set the baud rate in the Maestro Control Center that the Maestro is expecting, and you then need to initialize the Arduino hardware or serial port to the same baud rate. [This line in the Basic example](https://github.com/pololu/maestro-arduino/blob/master/examples/Basic/Basic.ino#L45) shows how to set the Arduino serial baud rate.

Ryan
